name: Test with Gradle, Docker Compose, and MySQL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: root
        ports:
          - 3307:3306

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
        with:
          gradle-version: '8.5'

      # Start the Docker Compose services
      - name: Start Docker Compose
        run: docker-compose -f compose.yml up

      - name: Build with Gradle 8.5
        run: gradle build

      - name: Run tests
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/sample
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root
        run: gradle test --info

      # Stop and remove the Docker Compose services
      - name: Stop Docker Compose
        run: docker-compose -f compose.yml down

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          job_name: 'Test Report'
